ALTER DATABASE QLDN_CAULONG 
SET RECOVERY FULL
GO

-- T1 – THỨ HAI 02:00 AM → FULL BACKUP
BACKUP DATABASE QLDN_CAULONG
    TO DISK = 'C:\Users\nguye\Desktop\DoAn_CauLong\FILE_BACKUP\QLDN_CAULONG_T1_Thu2_Full.bak'
    WITH INIT
GO

-- T2 – THỨ BA 02:00 AM → DIFFERENTIAL BACKUP
BACKUP DATABASE QLDN_CAULONG
    TO DISK = 'C:\Users\nguye\Desktop\DoAn_CauLong\FILE_BACKUP\QLDN_CAULONG_T2_Thu3_Diff.bak'
    WITH DIFFERENTIAL, INIT		
GO

-- T3 – THỨ TƯ 02:00 AM → LOG BACKUP
BACKUP LOG QLDN_CAULONG
    TO DISK = 'C:\Users\nguye\Desktop\DoAn_CauLong\FILE_BACKUP\QLDN_CAULONG_T3_Thu4_Log.trn'
    WITH INIT
GO

-- T4 – THỨ NĂM 02:00 AM → LOG BACKUP
BACKUP LOG QLDN_CAULONG
    TO DISK = 'C:\Users\nguye\Desktop\DoAn_CauLong\FILE_BACKUP\QLDN_CAULONG_T4_Thu5_Log.trn'
    WITH INIT
GO

-- T5 – THỨ SÁU 02:00 AM → DIFFERENTIAL BACKUP
BACKUP DATABASE QLDN_CAULONG
    TO DISK = 'C:\Users\nguye\Desktop\DoAn_CauLong\FILE_BACKUP\QLDN_CAULONG_T5_Thu6_Diff.bak'
    WITH DIFFERENTIAL, INIT
GO

-- T6 – THỨ BẢY 02:00 AM → LOG BACKUP
BACKUP LOG QLDN_CAULONG
    TO DISK = 'C:\Users\nguye\Desktop\DoAn_CauLong\FILE_BACKUP\QLDN_CAULONG_T6_Thu7_Log.trn'
    WITH INIT
GO

-- T7 – CHỦ NHẬT 02:00 AM → LOG BACKUP
BACKUP LOG QLDN_CAULONG
    TO DISK = 'C:\Users\nguye\Desktop\DoAn_CauLong\FILE_BACKUP\QLDN_CAULONG_T7_CN_Log.trn'
    WITH INIT
GO