//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_CauLong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichSuThayDoiGia
    {
        public int MaLichSu { get; set; }
        public int MaChiTiet { get; set; }
        public decimal GiaCu { get; set; }
        public decimal GiaMoi { get; set; }
        public int SoLuongCu { get; set; }
        public int SoLuongMoi { get; set; }
        public Nullable<System.DateTime> ThoiGianThayDoi { get; set; }
        public string NguoiThayDoi { get; set; }
    
        public virtual ChiTietSanPham ChiTietSanPham { get; set; }
    }
}
