//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_CauLong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogLoiGiaoTac
    {
        public int MaLog { get; set; }
        public Nullable<int> MaChiTiet { get; set; }
        public string Loi { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
        public string NguoiThucHien { get; set; }
    }
}
