//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_CauLong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanHoi
    {
        public int MaPhanHoi { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> NgayPhanHoi { get; set; }
        public Nullable<int> DanhGia { get; set; }
        public Nullable<int> MaKhachHang { get; set; }
        public Nullable<int> MaSanPham { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
