//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_CauLong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongSoVot
    {
        public int MaThongSo { get; set; }
        public Nullable<int> MaChiTiet { get; set; }
        public string DoCanBang { get; set; }
        public string TrongLuong { get; set; }
        public string DoCung { get; set; }
        public string ChieuDai { get; set; }
        public string SucCang { get; set; }
    
        public virtual ChiTietSanPham ChiTietSanPham { get; set; }
    }
}
